### ISSUE TITLE
'cd' causes an error

### ISSUE THREAD

**Issue by grovesteyn** [astronouth7303/xontrib-z#2] opened 2016-09-05 14:59 UTC
When I change directories with 'cd' I get the following debug info:

grove@grove-UX302LG ~ $ cd
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/xontrib/z.py", line 205, in cd_handler
self.add(self.getpwd())
File "/usr/local/lib/python3.4/dist-packages/xontrib/z.py", line 177, in add
data = list(self.load_data())
File "/usr/local/lib/python3.4/dist-packages/xontrib/z.py", line 85, in load_data
with open(self.Z_DATA, 'rt') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/grove/.z'

Any ideas?

**Comment by astronouth7303** [comment] 2016-09-05 15:01
Looks like I don't check for the existence of the data file.

**Comment by grovesteyn** [comment] 2016-09-05 15:10
Yes, I created in manually and the error disappears.
However, after moving around a bit I do "cat .z" but its empty?

**Comment by astronouth7303** [comment] 2016-09-05 15:10
Odd. I'll have to investigate.

**Comment by astronouth7303** [comment] 2016-09-05 15:20
Ok, the initial missing file should be taken care of in HEAD.

I'm able to reproduce the empty data bug. Not sure why that's happening.

**Comment by astronouth7303** [comment] 2016-09-05 15:35
Ok, Linux wasn't actually writing out the file yet when I was doing the copy. Should be fixed in HEAD.

**Comment by astronouth7303** [comment] 2016-09-06 02:21
Release made. If I don't hear in the next few days, I'm going to assume this is fixed.

**Comment by grovesteyn** [comment] 2016-09-06 09:35
Thanks - it seems to work!

G

**Closed** 2016-09-06 13:15 UTC
